<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260606202124 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cleaning_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scheduled_date DATE NOT NULL, scheduled_time TIME(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, property_id INT NOT NULL, service_id INT NOT NULL, assigned_cleaner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17C90236549213EC ON cleaning_request (property_id)');
        $this->addSql('CREATE INDEX IDX_17C90236ED5CA9E6 ON cleaning_request (service_id)');
        $this->addSql('CREATE INDEX IDX_17C90236D57CCD68 ON cleaning_request (assigned_cleaner_id)');
        $this->addSql('ALTER TABLE cleaning_request ADD CONSTRAINT FK_17C90236549213EC FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cleaning_request ADD CONSTRAINT FK_17C90236ED5CA9E6 FOREIGN KEY (service_id) REFERENCES cleaning_service (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cleaning_request ADD CONSTRAINT FK_17C90236D57CCD68 FOREIGN KEY (assigned_cleaner_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cleaning_request DROP CONSTRAINT FK_17C90236549213EC');
        $this->addSql('ALTER TABLE cleaning_request DROP CONSTRAINT FK_17C90236ED5CA9E6');
        $this->addSql('ALTER TABLE cleaning_request DROP CONSTRAINT FK_17C90236D57CCD68');
        $this->addSql('DROP TABLE cleaning_request');
    }
}
