<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260615201750 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lead_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, result VARCHAR(20) DEFAULT NULL, note TEXT DEFAULT NULL, activity_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, follow_up_date DATE DEFAULT NULL, lead_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6278B5955458D ON lead_activity (lead_id)');
        $this->addSql('ALTER TABLE lead_activity ADD CONSTRAINT FK_6278B5955458D FOREIGN KEY (lead_id) REFERENCES lead (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lead_activity DROP CONSTRAINT FK_6278B5955458D');
        $this->addSql('DROP TABLE lead_activity');
    }
}
