<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260615192841 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lead_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, score_bonus INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE lead ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CB12469DE2 FOREIGN KEY (category_id) REFERENCES lead_category (id)');
        $this->addSql('CREATE INDEX IDX_289161CB12469DE2 ON lead (category_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE lead_category');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CB12469DE2');
        $this->addSql('DROP INDEX IDX_289161CB12469DE2');
        $this->addSql('ALTER TABLE lead DROP category_id');
    }
}
