<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616120356 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE devis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total DOUBLE PRECISION NOT NULL, discount DOUBLE PRECISION DEFAULT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lead_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B27C52B55458D ON devis (lead_id)');
        $this->addSql('CREATE TABLE devis_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire DOUBLE PRECISION NOT NULL, description VARCHAR(255) DEFAULT NULL, devis_id INT NOT NULL, tarif_prestation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_41D3C6A741DEFADA ON devis_ligne (devis_id)');
        $this->addSql('CREATE INDEX IDX_41D3C6A797EFAB4B ON devis_ligne (tarif_prestation_id)');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52B55458D FOREIGN KEY (lead_id) REFERENCES lead (id)');
        $this->addSql('ALTER TABLE devis_ligne ADD CONSTRAINT FK_41D3C6A741DEFADA FOREIGN KEY (devis_id) REFERENCES devis (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE devis_ligne ADD CONSTRAINT FK_41D3C6A797EFAB4B FOREIGN KEY (tarif_prestation_id) REFERENCES tarif_prestation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE devis DROP CONSTRAINT FK_8B27C52B55458D');
        $this->addSql('ALTER TABLE devis_ligne DROP CONSTRAINT FK_41D3C6A741DEFADA');
        $this->addSql('ALTER TABLE devis_ligne DROP CONSTRAINT FK_41D3C6A797EFAB4B');
        $this->addSql('DROP TABLE devis');
        $this->addSql('DROP TABLE devis_ligne');
    }
}
