<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625192313 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sync_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(20) NOT NULL, source VARCHAR(20) NOT NULL, message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cleaning_request_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3171117696294493 ON sync_log (cleaning_request_id)');
        $this->addSql('ALTER TABLE sync_log ADD CONSTRAINT FK_3171117696294493 FOREIGN KEY (cleaning_request_id) REFERENCES cleaning_request (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sync_log DROP CONSTRAINT FK_3171117696294493');
        $this->addSql('DROP TABLE sync_log');
    }
}
